name: Update GBFS
on:
  schedule:
    # - cron:  '0 10 * * *'
    - cron:  */5 * * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        cd scripts && pipenv install
    - name: Fetch latest data
      run: |-
        python scripts/convert-gbfs-csv-to-dmfr.py > feeds/nabsa.github.com.dmfr.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated GBFS feeds from https://github.com/NABSA/gbfs/blob/master/systems.csv at ${timestamp}" || exit 0
        git push
