name: Validate Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: "TODO: source gotransit from its repo, rather than this hack"
      run: export PATH=$PATH:$(pwd)
    - name: Try to validate feeds
      run: cd scripts && python validate-feeds.py